type VboardScaleNameT =
	| 'A major pentatonic'
	| 'A major'
	| 'A minor'
	| 'A major blues'
	| 'A minor blues'
	| 'A melodic minor'
	| 'A harmonic minor'
	| 'A bebop'
	| 'A diminished'
	| 'A dorian'
	| 'A lydian'
	| 'A mixolydian'
	| 'A phrygian'
	| 'A locrian'
	| 'A ionian pentatonic'
	| 'A mixolydian pentatonic'
	| 'A ritusen'
	| 'A egyptian'
	| 'A neopolitan major pentatonic'
	| 'A vietnamese 1'
	| 'A pelog'
	| 'A kumoijoshi'
	| 'A hirajoshi'
	| 'A iwato'
	| 'A in-sen'
	| 'A lydian pentatonic'
	| 'A malkos raga'
	| 'A locrian pentatonic'
	| 'A minor pentatonic'
	| 'A minor six pentatonic'
	| 'A flat three pentatonic'
	| 'A flat six pentatonic'
	| 'A scriabin'
	| 'A whole tone pentatonic'
	| 'A lydian dominant pentatonic'
	| 'A minor #7M pentatonic'
	| 'A super locrian pentatonic'
	| 'A minor hexatonic'
	| 'A augmented'
	| 'A piongio'
	| 'A prometheus neopolitan'
	| 'A prometheus'
	| 'A mystery #1'
	| 'A six tone symmetric'
	| 'A whole tone'
	| "A messiaen's mode #5"
	| 'A locrian major'
	| 'A double harmonic lydian'
	| 'A altered'
	| 'A locrian #2'
	| 'A mixolydian b6'
	| 'A lydian dominant'
	| 'A lydian augmented'
	| 'A dorian b2'
	| 'A ultralocrian'
	| 'A locrian 6'
	| 'A augmented heptatonic'
	| 'A dorian #4'
	| 'A lydian diminished'
	| 'A leading whole tone'
	| 'A lydian minor'
	| 'A phrygian dominant'
	| 'A balinese'
	| 'A neopolitan major'
	| 'A harmonic major'
	| 'A double harmonic major'
	| 'A hungarian minor'
	| 'A hungarian major'
	| 'A oriental'
	| 'A flamenco'
	| 'A todi raga'
	| 'A persian'
	| 'A enigmatic'
	| 'A major augmented'
	| 'A lydian #9'
	| "A messiaen's mode #4"
	| 'A purvi raga'
	| 'A spanish heptatonic'
	| 'A bebop minor'
	| 'A bebop major'
	| 'A bebop locrian'
	| 'A minor bebop'
	| 'A ichikosucho'
	| 'A minor six diminished'
	| 'A half-whole diminished'
	| 'A kafi raga'
	| "A messiaen's mode #6"
	| 'A composite blues'
	| "A messiaen's mode #3"
	| "A messiaen's mode #7"
	| 'A chromatic'
	| 'A# major pentatonic'
	| 'A# major'
	| 'A# minor'
	| 'A# major blues'
	| 'A# minor blues'
	| 'A# melodic minor'
	| 'A# harmonic minor'
	| 'A# bebop'
	| 'A# diminished'
	| 'A# dorian'
	| 'A# lydian'
	| 'A# mixolydian'
	| 'A# phrygian'
	| 'A# locrian'
	| 'A# ionian pentatonic'
	| 'A# mixolydian pentatonic'
	| 'A# ritusen'
	| 'A# egyptian'
	| 'A# neopolitan major pentatonic'
	| 'A# vietnamese 1'
	| 'A# pelog'
	| 'A# kumoijoshi'
	| 'A# hirajoshi'
	| 'A# iwato'
	| 'A# in-sen'
	| 'A# lydian pentatonic'
	| 'A# malkos raga'
	| 'A# locrian pentatonic'
	| 'A# minor pentatonic'
	| 'A# minor six pentatonic'
	| 'A# flat three pentatonic'
	| 'A# flat six pentatonic'
	| 'A# scriabin'
	| 'A# whole tone pentatonic'
	| 'A# lydian dominant pentatonic'
	| 'A# minor #7M pentatonic'
	| 'A# super locrian pentatonic'
	| 'A# minor hexatonic'
	| 'A# augmented'
	| 'A# piongio'
	| 'A# prometheus neopolitan'
	| 'A# prometheus'
	| 'A# mystery #1'
	| 'A# six tone symmetric'
	| 'A# whole tone'
	| "A# messiaen's mode #5"
	| 'A# locrian major'
	| 'A# double harmonic lydian'
	| 'A# altered'
	| 'A# locrian #2'
	| 'A# mixolydian b6'
	| 'A# lydian dominant'
	| 'A# lydian augmented'
	| 'A# dorian b2'
	| 'A# ultralocrian'
	| 'A# locrian 6'
	| 'A# augmented heptatonic'
	| 'A# dorian #4'
	| 'A# lydian diminished'
	| 'A# leading whole tone'
	| 'A# lydian minor'
	| 'A# phrygian dominant'
	| 'A# balinese'
	| 'A# neopolitan major'
	| 'A# harmonic major'
	| 'A# double harmonic major'
	| 'A# hungarian minor'
	| 'A# hungarian major'
	| 'A# oriental'
	| 'A# flamenco'
	| 'A# todi raga'
	| 'A# persian'
	| 'A# enigmatic'
	| 'A# major augmented'
	| 'A# lydian #9'
	| "A# messiaen's mode #4"
	| 'A# purvi raga'
	| 'A# spanish heptatonic'
	| 'A# bebop minor'
	| 'A# bebop major'
	| 'A# bebop locrian'
	| 'A# minor bebop'
	| 'A# ichikosucho'
	| 'A# minor six diminished'
	| 'A# half-whole diminished'
	| 'A# kafi raga'
	| "A# messiaen's mode #6"
	| 'A# composite blues'
	| "A# messiaen's mode #3"
	| "A# messiaen's mode #7"
	| 'A# chromatic'
	| 'B major pentatonic'
	| 'B major'
	| 'B minor'
	| 'B major blues'
	| 'B minor blues'
	| 'B melodic minor'
	| 'B harmonic minor'
	| 'B bebop'
	| 'B diminished'
	| 'B dorian'
	| 'B lydian'
	| 'B mixolydian'
	| 'B phrygian'
	| 'B locrian'
	| 'B ionian pentatonic'
	| 'B mixolydian pentatonic'
	| 'B ritusen'
	| 'B egyptian'
	| 'B neopolitan major pentatonic'
	| 'B vietnamese 1'
	| 'B pelog'
	| 'B kumoijoshi'
	| 'B hirajoshi'
	| 'B iwato'
	| 'B in-sen'
	| 'B lydian pentatonic'
	| 'B malkos raga'
	| 'B locrian pentatonic'
	| 'B minor pentatonic'
	| 'B minor six pentatonic'
	| 'B flat three pentatonic'
	| 'B flat six pentatonic'
	| 'B scriabin'
	| 'B whole tone pentatonic'
	| 'B lydian dominant pentatonic'
	| 'B minor #7M pentatonic'
	| 'B super locrian pentatonic'
	| 'B minor hexatonic'
	| 'B augmented'
	| 'B piongio'
	| 'B prometheus neopolitan'
	| 'B prometheus'
	| 'B mystery #1'
	| 'B six tone symmetric'
	| 'B whole tone'
	| "B messiaen's mode #5"
	| 'B locrian major'
	| 'B double harmonic lydian'
	| 'B altered'
	| 'B locrian #2'
	| 'B mixolydian b6'
	| 'B lydian dominant'
	| 'B lydian augmented'
	| 'B dorian b2'
	| 'B ultralocrian'
	| 'B locrian 6'
	| 'B augmented heptatonic'
	| 'B dorian #4'
	| 'B lydian diminished'
	| 'B leading whole tone'
	| 'B lydian minor'
	| 'B phrygian dominant'
	| 'B balinese'
	| 'B neopolitan major'
	| 'B harmonic major'
	| 'B double harmonic major'
	| 'B hungarian minor'
	| 'B hungarian major'
	| 'B oriental'
	| 'B flamenco'
	| 'B todi raga'
	| 'B persian'
	| 'B enigmatic'
	| 'B major augmented'
	| 'B lydian #9'
	| "B messiaen's mode #4"
	| 'B purvi raga'
	| 'B spanish heptatonic'
	| 'B bebop minor'
	| 'B bebop major'
	| 'B bebop locrian'
	| 'B minor bebop'
	| 'B ichikosucho'
	| 'B minor six diminished'
	| 'B half-whole diminished'
	| 'B kafi raga'
	| "B messiaen's mode #6"
	| 'B composite blues'
	| "B messiaen's mode #3"
	| "B messiaen's mode #7"
	| 'B chromatic'
	| 'C major pentatonic'
	| 'C major'
	| 'C minor'
	| 'C major blues'
	| 'C minor blues'
	| 'C melodic minor'
	| 'C harmonic minor'
	| 'C bebop'
	| 'C diminished'
	| 'C dorian'
	| 'C lydian'
	| 'C mixolydian'
	| 'C phrygian'
	| 'C locrian'
	| 'C ionian pentatonic'
	| 'C mixolydian pentatonic'
	| 'C ritusen'
	| 'C egyptian'
	| 'C neopolitan major pentatonic'
	| 'C vietnamese 1'
	| 'C pelog'
	| 'C kumoijoshi'
	| 'C hirajoshi'
	| 'C iwato'
	| 'C in-sen'
	| 'C lydian pentatonic'
	| 'C malkos raga'
	| 'C locrian pentatonic'
	| 'C minor pentatonic'
	| 'C minor six pentatonic'
	| 'C flat three pentatonic'
	| 'C flat six pentatonic'
	| 'C scriabin'
	| 'C whole tone pentatonic'
	| 'C lydian dominant pentatonic'
	| 'C minor #7M pentatonic'
	| 'C super locrian pentatonic'
	| 'C minor hexatonic'
	| 'C augmented'
	| 'C piongio'
	| 'C prometheus neopolitan'
	| 'C prometheus'
	| 'C mystery #1'
	| 'C six tone symmetric'
	| 'C whole tone'
	| "C messiaen's mode #5"
	| 'C locrian major'
	| 'C double harmonic lydian'
	| 'C altered'
	| 'C locrian #2'
	| 'C mixolydian b6'
	| 'C lydian dominant'
	| 'C lydian augmented'
	| 'C dorian b2'
	| 'C ultralocrian'
	| 'C locrian 6'
	| 'C augmented heptatonic'
	| 'C dorian #4'
	| 'C lydian diminished'
	| 'C leading whole tone'
	| 'C lydian minor'
	| 'C phrygian dominant'
	| 'C balinese'
	| 'C neopolitan major'
	| 'C harmonic major'
	| 'C double harmonic major'
	| 'C hungarian minor'
	| 'C hungarian major'
	| 'C oriental'
	| 'C flamenco'
	| 'C todi raga'
	| 'C persian'
	| 'C enigmatic'
	| 'C major augmented'
	| 'C lydian #9'
	| "C messiaen's mode #4"
	| 'C purvi raga'
	| 'C spanish heptatonic'
	| 'C bebop minor'
	| 'C bebop major'
	| 'C bebop locrian'
	| 'C minor bebop'
	| 'C ichikosucho'
	| 'C minor six diminished'
	| 'C half-whole diminished'
	| 'C kafi raga'
	| "C messiaen's mode #6"
	| 'C composite blues'
	| "C messiaen's mode #3"
	| "C messiaen's mode #7"
	| 'C chromatic'
	| 'C# major pentatonic'
	| 'C# major'
	| 'C# minor'
	| 'C# major blues'
	| 'C# minor blues'
	| 'C# melodic minor'
	| 'C# harmonic minor'
	| 'C# bebop'
	| 'C# diminished'
	| 'C# dorian'
	| 'C# lydian'
	| 'C# mixolydian'
	| 'C# phrygian'
	| 'C# locrian'
	| 'C# ionian pentatonic'
	| 'C# mixolydian pentatonic'
	| 'C# ritusen'
	| 'C# egyptian'
	| 'C# neopolitan major pentatonic'
	| 'C# vietnamese 1'
	| 'C# pelog'
	| 'C# kumoijoshi'
	| 'C# hirajoshi'
	| 'C# iwato'
	| 'C# in-sen'
	| 'C# lydian pentatonic'
	| 'C# malkos raga'
	| 'C# locrian pentatonic'
	| 'C# minor pentatonic'
	| 'C# minor six pentatonic'
	| 'C# flat three pentatonic'
	| 'C# flat six pentatonic'
	| 'C# scriabin'
	| 'C# whole tone pentatonic'
	| 'C# lydian dominant pentatonic'
	| 'C# minor #7M pentatonic'
	| 'C# super locrian pentatonic'
	| 'C# minor hexatonic'
	| 'C# augmented'
	| 'C# piongio'
	| 'C# prometheus neopolitan'
	| 'C# prometheus'
	| 'C# mystery #1'
	| 'C# six tone symmetric'
	| 'C# whole tone'
	| "C# messiaen's mode #5"
	| 'C# locrian major'
	| 'C# double harmonic lydian'
	| 'C# altered'
	| 'C# locrian #2'
	| 'C# mixolydian b6'
	| 'C# lydian dominant'
	| 'C# lydian augmented'
	| 'C# dorian b2'
	| 'C# ultralocrian'
	| 'C# locrian 6'
	| 'C# augmented heptatonic'
	| 'C# dorian #4'
	| 'C# lydian diminished'
	| 'C# leading whole tone'
	| 'C# lydian minor'
	| 'C# phrygian dominant'
	| 'C# balinese'
	| 'C# neopolitan major'
	| 'C# harmonic major'
	| 'C# double harmonic major'
	| 'C# hungarian minor'
	| 'C# hungarian major'
	| 'C# oriental'
	| 'C# flamenco'
	| 'C# todi raga'
	| 'C# persian'
	| 'C# enigmatic'
	| 'C# major augmented'
	| 'C# lydian #9'
	| "C# messiaen's mode #4"
	| 'C# purvi raga'
	| 'C# spanish heptatonic'
	| 'C# bebop minor'
	| 'C# bebop major'
	| 'C# bebop locrian'
	| 'C# minor bebop'
	| 'C# ichikosucho'
	| 'C# minor six diminished'
	| 'C# half-whole diminished'
	| 'C# kafi raga'
	| "C# messiaen's mode #6"
	| 'C# composite blues'
	| "C# messiaen's mode #3"
	| "C# messiaen's mode #7"
	| 'C# chromatic'
	| 'D major pentatonic'
	| 'D major'
	| 'D minor'
	| 'D major blues'
	| 'D minor blues'
	| 'D melodic minor'
	| 'D harmonic minor'
	| 'D bebop'
	| 'D diminished'
	| 'D dorian'
	| 'D lydian'
	| 'D mixolydian'
	| 'D phrygian'
	| 'D locrian'
	| 'D ionian pentatonic'
	| 'D mixolydian pentatonic'
	| 'D ritusen'
	| 'D egyptian'
	| 'D neopolitan major pentatonic'
	| 'D vietnamese 1'
	| 'D pelog'
	| 'D kumoijoshi'
	| 'D hirajoshi'
	| 'D iwato'
	| 'D in-sen'
	| 'D lydian pentatonic'
	| 'D malkos raga'
	| 'D locrian pentatonic'
	| 'D minor pentatonic'
	| 'D minor six pentatonic'
	| 'D flat three pentatonic'
	| 'D flat six pentatonic'
	| 'D scriabin'
	| 'D whole tone pentatonic'
	| 'D lydian dominant pentatonic'
	| 'D minor #7M pentatonic'
	| 'D super locrian pentatonic'
	| 'D minor hexatonic'
	| 'D augmented'
	| 'D piongio'
	| 'D prometheus neopolitan'
	| 'D prometheus'
	| 'D mystery #1'
	| 'D six tone symmetric'
	| 'D whole tone'
	| "D messiaen's mode #5"
	| 'D locrian major'
	| 'D double harmonic lydian'
	| 'D altered'
	| 'D locrian #2'
	| 'D mixolydian b6'
	| 'D lydian dominant'
	| 'D lydian augmented'
	| 'D dorian b2'
	| 'D ultralocrian'
	| 'D locrian 6'
	| 'D augmented heptatonic'
	| 'D dorian #4'
	| 'D lydian diminished'
	| 'D leading whole tone'
	| 'D lydian minor'
	| 'D phrygian dominant'
	| 'D balinese'
	| 'D neopolitan major'
	| 'D harmonic major'
	| 'D double harmonic major'
	| 'D hungarian minor'
	| 'D hungarian major'
	| 'D oriental'
	| 'D flamenco'
	| 'D todi raga'
	| 'D persian'
	| 'D enigmatic'
	| 'D major augmented'
	| 'D lydian #9'
	| "D messiaen's mode #4"
	| 'D purvi raga'
	| 'D spanish heptatonic'
	| 'D bebop minor'
	| 'D bebop major'
	| 'D bebop locrian'
	| 'D minor bebop'
	| 'D ichikosucho'
	| 'D minor six diminished'
	| 'D half-whole diminished'
	| 'D kafi raga'
	| "D messiaen's mode #6"
	| 'D composite blues'
	| "D messiaen's mode #3"
	| "D messiaen's mode #7"
	| 'D chromatic'
	| 'D# major pentatonic'
	| 'D# major'
	| 'D# minor'
	| 'D# major blues'
	| 'D# minor blues'
	| 'D# melodic minor'
	| 'D# harmonic minor'
	| 'D# bebop'
	| 'D# diminished'
	| 'D# dorian'
	| 'D# lydian'
	| 'D# mixolydian'
	| 'D# phrygian'
	| 'D# locrian'
	| 'D# ionian pentatonic'
	| 'D# mixolydian pentatonic'
	| 'D# ritusen'
	| 'D# egyptian'
	| 'D# neopolitan major pentatonic'
	| 'D# vietnamese 1'
	| 'D# pelog'
	| 'D# kumoijoshi'
	| 'D# hirajoshi'
	| 'D# iwato'
	| 'D# in-sen'
	| 'D# lydian pentatonic'
	| 'D# malkos raga'
	| 'D# locrian pentatonic'
	| 'D# minor pentatonic'
	| 'D# minor six pentatonic'
	| 'D# flat three pentatonic'
	| 'D# flat six pentatonic'
	| 'D# scriabin'
	| 'D# whole tone pentatonic'
	| 'D# lydian dominant pentatonic'
	| 'D# minor #7M pentatonic'
	| 'D# super locrian pentatonic'
	| 'D# minor hexatonic'
	| 'D# augmented'
	| 'D# piongio'
	| 'D# prometheus neopolitan'
	| 'D# prometheus'
	| 'D# mystery #1'
	| 'D# six tone symmetric'
	| 'D# whole tone'
	| "D# messiaen's mode #5"
	| 'D# locrian major'
	| 'D# double harmonic lydian'
	| 'D# altered'
	| 'D# locrian #2'
	| 'D# mixolydian b6'
	| 'D# lydian dominant'
	| 'D# lydian augmented'
	| 'D# dorian b2'
	| 'D# ultralocrian'
	| 'D# locrian 6'
	| 'D# augmented heptatonic'
	| 'D# dorian #4'
	| 'D# lydian diminished'
	| 'D# leading whole tone'
	| 'D# lydian minor'
	| 'D# phrygian dominant'
	| 'D# balinese'
	| 'D# neopolitan major'
	| 'D# harmonic major'
	| 'D# double harmonic major'
	| 'D# hungarian minor'
	| 'D# hungarian major'
	| 'D# oriental'
	| 'D# flamenco'
	| 'D# todi raga'
	| 'D# persian'
	| 'D# enigmatic'
	| 'D# major augmented'
	| 'D# lydian #9'
	| "D# messiaen's mode #4"
	| 'D# purvi raga'
	| 'D# spanish heptatonic'
	| 'D# bebop minor'
	| 'D# bebop major'
	| 'D# bebop locrian'
	| 'D# minor bebop'
	| 'D# ichikosucho'
	| 'D# minor six diminished'
	| 'D# half-whole diminished'
	| 'D# kafi raga'
	| "D# messiaen's mode #6"
	| 'D# composite blues'
	| "D# messiaen's mode #3"
	| "D# messiaen's mode #7"
	| 'D# chromatic'
	| 'E major pentatonic'
	| 'E major'
	| 'E minor'
	| 'E major blues'
	| 'E minor blues'
	| 'E melodic minor'
	| 'E harmonic minor'
	| 'E bebop'
	| 'E diminished'
	| 'E dorian'
	| 'E lydian'
	| 'E mixolydian'
	| 'E phrygian'
	| 'E locrian'
	| 'E ionian pentatonic'
	| 'E mixolydian pentatonic'
	| 'E ritusen'
	| 'E egyptian'
	| 'E neopolitan major pentatonic'
	| 'E vietnamese 1'
	| 'E pelog'
	| 'E kumoijoshi'
	| 'E hirajoshi'
	| 'E iwato'
	| 'E in-sen'
	| 'E lydian pentatonic'
	| 'E malkos raga'
	| 'E locrian pentatonic'
	| 'E minor pentatonic'
	| 'E minor six pentatonic'
	| 'E flat three pentatonic'
	| 'E flat six pentatonic'
	| 'E scriabin'
	| 'E whole tone pentatonic'
	| 'E lydian dominant pentatonic'
	| 'E minor #7M pentatonic'
	| 'E super locrian pentatonic'
	| 'E minor hexatonic'
	| 'E augmented'
	| 'E piongio'
	| 'E prometheus neopolitan'
	| 'E prometheus'
	| 'E mystery #1'
	| 'E six tone symmetric'
	| 'E whole tone'
	| "E messiaen's mode #5"
	| 'E locrian major'
	| 'E double harmonic lydian'
	| 'E altered'
	| 'E locrian #2'
	| 'E mixolydian b6'
	| 'E lydian dominant'
	| 'E lydian augmented'
	| 'E dorian b2'
	| 'E ultralocrian'
	| 'E locrian 6'
	| 'E augmented heptatonic'
	| 'E dorian #4'
	| 'E lydian diminished'
	| 'E leading whole tone'
	| 'E lydian minor'
	| 'E phrygian dominant'
	| 'E balinese'
	| 'E neopolitan major'
	| 'E harmonic major'
	| 'E double harmonic major'
	| 'E hungarian minor'
	| 'E hungarian major'
	| 'E oriental'
	| 'E flamenco'
	| 'E todi raga'
	| 'E persian'
	| 'E enigmatic'
	| 'E major augmented'
	| 'E lydian #9'
	| "E messiaen's mode #4"
	| 'E purvi raga'
	| 'E spanish heptatonic'
	| 'E bebop minor'
	| 'E bebop major'
	| 'E bebop locrian'
	| 'E minor bebop'
	| 'E ichikosucho'
	| 'E minor six diminished'
	| 'E half-whole diminished'
	| 'E kafi raga'
	| "E messiaen's mode #6"
	| 'E composite blues'
	| "E messiaen's mode #3"
	| "E messiaen's mode #7"
	| 'E chromatic'
	| 'F major pentatonic'
	| 'F major'
	| 'F minor'
	| 'F major blues'
	| 'F minor blues'
	| 'F melodic minor'
	| 'F harmonic minor'
	| 'F bebop'
	| 'F diminished'
	| 'F dorian'
	| 'F lydian'
	| 'F mixolydian'
	| 'F phrygian'
	| 'F locrian'
	| 'F ionian pentatonic'
	| 'F mixolydian pentatonic'
	| 'F ritusen'
	| 'F egyptian'
	| 'F neopolitan major pentatonic'
	| 'F vietnamese 1'
	| 'F pelog'
	| 'F kumoijoshi'
	| 'F hirajoshi'
	| 'F iwato'
	| 'F in-sen'
	| 'F lydian pentatonic'
	| 'F malkos raga'
	| 'F locrian pentatonic'
	| 'F minor pentatonic'
	| 'F minor six pentatonic'
	| 'F flat three pentatonic'
	| 'F flat six pentatonic'
	| 'F scriabin'
	| 'F whole tone pentatonic'
	| 'F lydian dominant pentatonic'
	| 'F minor #7M pentatonic'
	| 'F super locrian pentatonic'
	| 'F minor hexatonic'
	| 'F augmented'
	| 'F piongio'
	| 'F prometheus neopolitan'
	| 'F prometheus'
	| 'F mystery #1'
	| 'F six tone symmetric'
	| 'F whole tone'
	| "F messiaen's mode #5"
	| 'F locrian major'
	| 'F double harmonic lydian'
	| 'F altered'
	| 'F locrian #2'
	| 'F mixolydian b6'
	| 'F lydian dominant'
	| 'F lydian augmented'
	| 'F dorian b2'
	| 'F ultralocrian'
	| 'F locrian 6'
	| 'F augmented heptatonic'
	| 'F dorian #4'
	| 'F lydian diminished'
	| 'F leading whole tone'
	| 'F lydian minor'
	| 'F phrygian dominant'
	| 'F balinese'
	| 'F neopolitan major'
	| 'F harmonic major'
	| 'F double harmonic major'
	| 'F hungarian minor'
	| 'F hungarian major'
	| 'F oriental'
	| 'F flamenco'
	| 'F todi raga'
	| 'F persian'
	| 'F enigmatic'
	| 'F major augmented'
	| 'F lydian #9'
	| "F messiaen's mode #4"
	| 'F purvi raga'
	| 'F spanish heptatonic'
	| 'F bebop minor'
	| 'F bebop major'
	| 'F bebop locrian'
	| 'F minor bebop'
	| 'F ichikosucho'
	| 'F minor six diminished'
	| 'F half-whole diminished'
	| 'F kafi raga'
	| "F messiaen's mode #6"
	| 'F composite blues'
	| "F messiaen's mode #3"
	| "F messiaen's mode #7"
	| 'F chromatic'
	| 'F# major pentatonic'
	| 'F# major'
	| 'F# minor'
	| 'F# major blues'
	| 'F# minor blues'
	| 'F# melodic minor'
	| 'F# harmonic minor'
	| 'F# bebop'
	| 'F# diminished'
	| 'F# dorian'
	| 'F# lydian'
	| 'F# mixolydian'
	| 'F# phrygian'
	| 'F# locrian'
	| 'F# ionian pentatonic'
	| 'F# mixolydian pentatonic'
	| 'F# ritusen'
	| 'F# egyptian'
	| 'F# neopolitan major pentatonic'
	| 'F# vietnamese 1'
	| 'F# pelog'
	| 'F# kumoijoshi'
	| 'F# hirajoshi'
	| 'F# iwato'
	| 'F# in-sen'
	| 'F# lydian pentatonic'
	| 'F# malkos raga'
	| 'F# locrian pentatonic'
	| 'F# minor pentatonic'
	| 'F# minor six pentatonic'
	| 'F# flat three pentatonic'
	| 'F# flat six pentatonic'
	| 'F# scriabin'
	| 'F# whole tone pentatonic'
	| 'F# lydian dominant pentatonic'
	| 'F# minor #7M pentatonic'
	| 'F# super locrian pentatonic'
	| 'F# minor hexatonic'
	| 'F# augmented'
	| 'F# piongio'
	| 'F# prometheus neopolitan'
	| 'F# prometheus'
	| 'F# mystery #1'
	| 'F# six tone symmetric'
	| 'F# whole tone'
	| "F# messiaen's mode #5"
	| 'F# locrian major'
	| 'F# double harmonic lydian'
	| 'F# altered'
	| 'F# locrian #2'
	| 'F# mixolydian b6'
	| 'F# lydian dominant'
	| 'F# lydian augmented'
	| 'F# dorian b2'
	| 'F# ultralocrian'
	| 'F# locrian 6'
	| 'F# augmented heptatonic'
	| 'F# dorian #4'
	| 'F# lydian diminished'
	| 'F# leading whole tone'
	| 'F# lydian minor'
	| 'F# phrygian dominant'
	| 'F# balinese'
	| 'F# neopolitan major'
	| 'F# harmonic major'
	| 'F# double harmonic major'
	| 'F# hungarian minor'
	| 'F# hungarian major'
	| 'F# oriental'
	| 'F# flamenco'
	| 'F# todi raga'
	| 'F# persian'
	| 'F# enigmatic'
	| 'F# major augmented'
	| 'F# lydian #9'
	| "F# messiaen's mode #4"
	| 'F# purvi raga'
	| 'F# spanish heptatonic'
	| 'F# bebop minor'
	| 'F# bebop major'
	| 'F# bebop locrian'
	| 'F# minor bebop'
	| 'F# ichikosucho'
	| 'F# minor six diminished'
	| 'F# half-whole diminished'
	| 'F# kafi raga'
	| "F# messiaen's mode #6"
	| 'F# composite blues'
	| "F# messiaen's mode #3"
	| "F# messiaen's mode #7"
	| 'F# chromatic'
	| 'G major pentatonic'
	| 'G major'
	| 'G minor'
	| 'G major blues'
	| 'G minor blues'
	| 'G melodic minor'
	| 'G harmonic minor'
	| 'G bebop'
	| 'G diminished'
	| 'G dorian'
	| 'G lydian'
	| 'G mixolydian'
	| 'G phrygian'
	| 'G locrian'
	| 'G ionian pentatonic'
	| 'G mixolydian pentatonic'
	| 'G ritusen'
	| 'G egyptian'
	| 'G neopolitan major pentatonic'
	| 'G vietnamese 1'
	| 'G pelog'
	| 'G kumoijoshi'
	| 'G hirajoshi'
	| 'G iwato'
	| 'G in-sen'
	| 'G lydian pentatonic'
	| 'G malkos raga'
	| 'G locrian pentatonic'
	| 'G minor pentatonic'
	| 'G minor six pentatonic'
	| 'G flat three pentatonic'
	| 'G flat six pentatonic'
	| 'G scriabin'
	| 'G whole tone pentatonic'
	| 'G lydian dominant pentatonic'
	| 'G minor #7M pentatonic'
	| 'G super locrian pentatonic'
	| 'G minor hexatonic'
	| 'G augmented'
	| 'G piongio'
	| 'G prometheus neopolitan'
	| 'G prometheus'
	| 'G mystery #1'
	| 'G six tone symmetric'
	| 'G whole tone'
	| "G messiaen's mode #5"
	| 'G locrian major'
	| 'G double harmonic lydian'
	| 'G altered'
	| 'G locrian #2'
	| 'G mixolydian b6'
	| 'G lydian dominant'
	| 'G lydian augmented'
	| 'G dorian b2'
	| 'G ultralocrian'
	| 'G locrian 6'
	| 'G augmented heptatonic'
	| 'G dorian #4'
	| 'G lydian diminished'
	| 'G leading whole tone'
	| 'G lydian minor'
	| 'G phrygian dominant'
	| 'G balinese'
	| 'G neopolitan major'
	| 'G harmonic major'
	| 'G double harmonic major'
	| 'G hungarian minor'
	| 'G hungarian major'
	| 'G oriental'
	| 'G flamenco'
	| 'G todi raga'
	| 'G persian'
	| 'G enigmatic'
	| 'G major augmented'
	| 'G lydian #9'
	| "G messiaen's mode #4"
	| 'G purvi raga'
	| 'G spanish heptatonic'
	| 'G bebop minor'
	| 'G bebop major'
	| 'G bebop locrian'
	| 'G minor bebop'
	| 'G ichikosucho'
	| 'G minor six diminished'
	| 'G half-whole diminished'
	| 'G kafi raga'
	| "G messiaen's mode #6"
	| 'G composite blues'
	| "G messiaen's mode #3"
	| "G messiaen's mode #7"
	| 'G chromatic'
	| 'G# major pentatonic'
	| 'G# major'
	| 'G# minor'
	| 'G# major blues'
	| 'G# minor blues'
	| 'G# melodic minor'
	| 'G# harmonic minor'
	| 'G# bebop'
	| 'G# diminished'
	| 'G# dorian'
	| 'G# lydian'
	| 'G# mixolydian'
	| 'G# phrygian'
	| 'G# locrian'
	| 'G# ionian pentatonic'
	| 'G# mixolydian pentatonic'
	| 'G# ritusen'
	| 'G# egyptian'
	| 'G# neopolitan major pentatonic'
	| 'G# vietnamese 1'
	| 'G# pelog'
	| 'G# kumoijoshi'
	| 'G# hirajoshi'
	| 'G# iwato'
	| 'G# in-sen'
	| 'G# lydian pentatonic'
	| 'G# malkos raga'
	| 'G# locrian pentatonic'
	| 'G# minor pentatonic'
	| 'G# minor six pentatonic'
	| 'G# flat three pentatonic'
	| 'G# flat six pentatonic'
	| 'G# scriabin'
	| 'G# whole tone pentatonic'
	| 'G# lydian dominant pentatonic'
	| 'G# minor #7M pentatonic'
	| 'G# super locrian pentatonic'
	| 'G# minor hexatonic'
	| 'G# augmented'
	| 'G# piongio'
	| 'G# prometheus neopolitan'
	| 'G# prometheus'
	| 'G# mystery #1'
	| 'G# six tone symmetric'
	| 'G# whole tone'
	| "G# messiaen's mode #5"
	| 'G# locrian major'
	| 'G# double harmonic lydian'
	| 'G# altered'
	| 'G# locrian #2'
	| 'G# mixolydian b6'
	| 'G# lydian dominant'
	| 'G# lydian augmented'
	| 'G# dorian b2'
	| 'G# ultralocrian'
	| 'G# locrian 6'
	| 'G# augmented heptatonic'
	| 'G# dorian #4'
	| 'G# lydian diminished'
	| 'G# leading whole tone'
	| 'G# lydian minor'
	| 'G# phrygian dominant'
	| 'G# balinese'
	| 'G# neopolitan major'
	| 'G# harmonic major'
	| 'G# double harmonic major'
	| 'G# hungarian minor'
	| 'G# hungarian major'
	| 'G# oriental'
	| 'G# flamenco'
	| 'G# todi raga'
	| 'G# persian'
	| 'G# enigmatic'
	| 'G# major augmented'
	| 'G# lydian #9'
	| "G# messiaen's mode #4"
	| 'G# purvi raga'
	| 'G# spanish heptatonic'
	| 'G# bebop minor'
	| 'G# bebop major'
	| 'G# bebop locrian'
	| 'G# minor bebop'
	| 'G# ichikosucho'
	| 'G# minor six diminished'
	| 'G# half-whole diminished'
	| 'G# kafi raga'
	| "G# messiaen's mode #6"
	| 'G# composite blues'
	| "G# messiaen's mode #3"
	| "G# messiaen's mode #7"
	| 'G# chromatic'
