export const CHORDS = {
	'C major': [
		'A 7(no3)',
		'A 7(sus4)',
		'A min',
		'A min add 11',
		'A min add 9',
		'A min(no5)',
		'A min11',
		'A min13',
		'A min7',
		'A min9',
		'A sus2',
		'A sus4',
		'B 7(no3)',
		'B 7(sus4)',
		'B dim',
		'B dim add 11',
		'B dim add 9',
		'B dim(no5)',
		'B dim11',
		'B dim13',
		'B dim7',
		'B dim9',
		'B sus2',
		'B sus4',
		'C 6(sus2)',
		'C 6(sus4)',
		'C 7(no3)',
		'C 7(sus4)',
		'C maj',
		'C maj add 11',
		'C maj add 9',
		'C maj(no5)',
		'C maj11',
		'C maj13',
		'C maj7',
		'C maj9',
		'C sus2',
		'C sus4',
		'D 7(no3)',
		'D 7(sus4)',
		'D dim #5',
		'D dim b9',
		'D min',
		'D min add 11',
		'D min add 9',
		'D min(no5)',
		'D min11',
		'D min13',
		'D min7',
		'D min9',
		'D sus2',
		'D sus4',
		'E 7(no3)',
		'E 7(sus4)',
		'E min',
		'E min add 11',
		'E min add 9',
		'E min(no5)',
		'E min11',
		'E min13',
		'E min7',
		'E min9',
		'E sus2',
		'E sus4',
		'F 7(no3)',
		'F 7(sus4)',
		'F maj',
		'F maj add 11',
		'F maj add 9',
		'F maj(no5)',
		'F maj11',
		'F maj13',
		'F maj7',
		'F maj9',
		'F sus2',
		'F sus4',
		'G 13(sus4)',
		'G 7(no3)',
		'G 7(sus4)',
		'G 9(sus4)',
		'G maj',
		'G maj add 11',
		'G maj add 9',
		'G maj(no5)',
		'G maj11',
		'G maj13',
		'G maj7',
		'G maj9',
		'G sus2',
		'G sus4'
	],
	'C minor': [
		'A# 7(no3)',
		'A# 7(sus4)',
		'A# maj',
		'A# maj add 11',
		'A# maj add 9',
		'A# maj(no5)',
		'A# maj11',
		'A# maj13',
		'A# maj7',
		'A# maj9',
		'A# sus2',
		'A# sus4',
		'C 6(sus2)',
		'C 6(sus4)',
		'C 7(no3)',
		'C 7(sus4)',
		'C min',
		'C min add 11',
		'C min add 9',
		'C min(no5)',
		'C min11',
		'C min13',
		'C min7',
		'C min9',
		'C sus2',
		'C sus4',
		'D 7(no3)',
		'D 7(sus4)',
		'D dim',
		'D dim #5',
		'D dim add 11',
		'D dim add 9',
		'D dim b9',
		'D dim(no5)',
		'D dim11',
		'D dim13',
		'D dim7',
		'D dim9',
		'D sus2',
		'D sus4',
		'D# 7(no3)',
		'D# 7(sus4)',
		'D# min',
		'D# min add 11',
		'D# min add 9',
		'D# min(no5)',
		'D# min11',
		'D# min13',
		'D# min7',
		'D# min9',
		'D# sus2',
		'D# sus4',
		'F 7(no3)',
		'F 7(sus4)',
		'F maj',
		'F maj add 11',
		'F maj add 9',
		'F maj(no5)',
		'F maj11',
		'F maj13',
		'F maj7',
		'F maj9',
		'F sus2',
		'F sus4',
		'G 13(sus4)',
		'G 7(no3)',
		'G 7(sus4)',
		'G 9(sus4)',
		'G maj',
		'G maj add 11',
		'G maj add 9',
		'G maj(no5)',
		'G maj11',
		'G maj13',
		'G maj7',
		'G maj9',
		'G sus2',
		'G sus4',
		'G# 7(no3)',
		'G# 7(sus4)',
		'G# min',
		'G# min add 11',
		'G# min add 9',
		'G# min(no5)',
		'G# min11',
		'G# min13',
		'G# min7',
		'G# min9',
		'G# sus2',
		'G# sus4'
	],
	'C# major': [
		'A# 7(no3)',
		'A# 7(sus4)',
		'A# min',
		'A# min add 11',
		'A# min add 9',
		'A# min(no5)',
		'A# min11',
		'A# min13',
		'A# min7',
		'A# min9',
		'A# sus2',
		'A# sus4',
		'C 7(no3)',
		'C 7(sus4)',
		'C dim',
		'C dim add 11',
		'C dim add 9',
		'C dim(no5)',
		'C dim11',
		'C dim13',
		'C dim7',
		'C dim9',
		'C sus2',
		'C sus4',
		'C# 6(sus2)',
		'C# 6(sus4)',
		'C# 7(no3)',
		'C# 7(sus4)',
		'C# maj',
		'C# maj add 11',
		'C# maj add 9',
		'C# maj(no5)',
		'C# maj11',
		'C# maj13',
		'C# maj7',
		'C# maj9',
		'C# sus2',
		'C# sus4',
		'D# 7(no3)',
		'D# 7(sus4)',
		'D# dim #5',
		'D# dim b9',
		'D# min',
		'D# min add 11',
		'D# min add 9',
		'D# min(no5)',
		'D# min11',
		'D# min13',
		'D# min7',
		'D# min9',
		'D# sus2',
		'D# sus4',
		'F 7(no3)',
		'F 7(sus4)',
		'F min',
		'F min add 11',
		'F min add 9',
		'F min(no5)',
		'F min11',
		'F min13',
		'F min7',
		'F min9',
		'F sus2',
		'F sus4',
		'F# 7(no3)',
		'F# 7(sus4)',
		'F# maj',
		'F# maj add 11',
		'F# maj add 9',
		'F# maj(no5)',
		'F# maj11',
		'F# maj13',
		'F# maj7',
		'F# maj9',
		'F# sus2',
		'F# sus4',
		'G# 13(sus4)',
		'G# 7(no3)',
		'G# 7(sus4)',
		'G# 9(sus4)',
		'G# maj',
		'G# maj add 11',
		'G# maj add 9',
		'G# maj(no5)',
		'G# maj11',
		'G# maj13',
		'G# maj7',
		'G# maj9',
		'G# sus2',
		'G# sus4'
	],
	'C# minor': [
		'A 7(no3)',
		'A 7(sus4)',
		'A min',
		'A min add 11',
		'A min add 9',
		'A min(no5)',
		'A min11',
		'A min13',
		'A min7',
		'A min9',
		'A sus2',
		'A sus4',
		'B 7(no3)',
		'B 7(sus4)',
		'B maj',
		'B maj add 11',
		'B maj add 9',
		'B maj(no5)',
		'B maj11',
		'B maj13',
		'B maj7',
		'B maj9',
		'B sus2',
		'B sus4',
		'C# 6(sus2)',
		'C# 6(sus4)',
		'C# 7(no3)',
		'C# 7(sus4)',
		'C# min',
		'C# min add 11',
		'C# min add 9',
		'C# min(no5)',
		'C# min11',
		'C# min13',
		'C# min7',
		'C# min9',
		'C# sus2',
		'C# sus4',
		'D# 7(no3)',
		'D# 7(sus4)',
		'D# dim',
		'D# dim #5',
		'D# dim add 11',
		'D# dim add 9',
		'D# dim b9',
		'D# dim(no5)',
		'D# dim11',
		'D# dim13',
		'D# dim7',
		'D# dim9',
		'D# sus2',
		'D# sus4',
		'E 7(no3)',
		'E 7(sus4)',
		'E min',
		'E min add 11',
		'E min add 9',
		'E min(no5)',
		'E min11',
		'E min13',
		'E min7',
		'E min9',
		'E sus2',
		'E sus4',
		'F# 7(no3)',
		'F# 7(sus4)',
		'F# maj',
		'F# maj add 11',
		'F# maj add 9',
		'F# maj(no5)',
		'F# maj11',
		'F# maj13',
		'F# maj7',
		'F# maj9',
		'F# sus2',
		'F# sus4',
		'G# 13(sus4)',
		'G# 7(no3)',
		'G# 7(sus4)',
		'G# 9(sus4)',
		'G# maj',
		'G# maj add 11',
		'G# maj add 9',
		'G# maj(no5)',
		'G# maj11',
		'G# maj13',
		'G# maj7',
		'G# maj9',
		'G# sus2',
		'G# sus4'
	],
	'D major': [
		'A 13(sus4)',
		'A 7(no3)',
		'A 7(sus4)',
		'A 9(sus4)',
		'A maj',
		'A maj add 11',
		'A maj add 9',
		'A maj(no5)',
		'A maj11',
		'A maj13',
		'A maj7',
		'A maj9',
		'A sus2',
		'A sus4',
		'B 7(no3)',
		'B 7(sus4)',
		'B min',
		'B min add 11',
		'B min add 9',
		'B min(no5)',
		'B min11',
		'B min13',
		'B min7',
		'B min9',
		'B sus2',
		'B sus4',
		'C# 7(no3)',
		'C# 7(sus4)',
		'C# dim',
		'C# dim add 11',
		'C# dim add 9',
		'C# dim(no5)',
		'C# dim11',
		'C# dim13',
		'C# dim7',
		'C# dim9',
		'C# sus2',
		'C# sus4',
		'D 6(sus2)',
		'D 6(sus4)',
		'D 7(no3)',
		'D 7(sus4)',
		'D maj',
		'D maj add 11',
		'D maj add 9',
		'D maj(no5)',
		'D maj11',
		'D maj13',
		'D maj7',
		'D maj9',
		'D sus2',
		'D sus4',
		'E 7(no3)',
		'E 7(sus4)',
		'E dim #5',
		'E dim b9',
		'E min',
		'E min add 11',
		'E min add 9',
		'E min(no5)',
		'E min11',
		'E min13',
		'E min7',
		'E min9',
		'E sus2',
		'E sus4',
		'F# 7(no3)',
		'F# 7(sus4)',
		'F# min',
		'F# min add 11',
		'F# min add 9',
		'F# min(no5)',
		'F# min11',
		'F# min13',
		'F# min7',
		'F# min9',
		'F# sus2',
		'F# sus4',
		'G 7(no3)',
		'G 7(sus4)',
		'G maj',
		'G maj add 11',
		'G maj add 9',
		'G maj(no5)',
		'G maj11',
		'G maj13',
		'G maj7',
		'G maj9',
		'G sus2',
		'G sus4'
	],
	'D minor': [
		'A 13(sus4)',
		'A 7(no3)',
		'A 7(sus4)',
		'A 9(sus4)',
		'A maj',
		'A maj add 11',
		'A maj add 9',
		'A maj(no5)',
		'A maj11',
		'A maj13',
		'A maj7',
		'A maj9',
		'A sus2',
		'A sus4',
		'A# 7(no3)',
		'A# 7(sus4)',
		'A# min',
		'A# min add 11',
		'A# min add 9',
		'A# min(no5)',
		'A# min11',
		'A# min13',
		'A# min7',
		'A# min9',
		'A# sus2',
		'A# sus4',
		'C 7(no3)',
		'C 7(sus4)',
		'C maj',
		'C maj add 11',
		'C maj add 9',
		'C maj(no5)',
		'C maj11',
		'C maj13',
		'C maj7',
		'C maj9',
		'C sus2',
		'C sus4',
		'D 6(sus2)',
		'D 6(sus4)',
		'D 7(no3)',
		'D 7(sus4)',
		'D min',
		'D min add 11',
		'D min add 9',
		'D min(no5)',
		'D min11',
		'D min13',
		'D min7',
		'D min9',
		'D sus2',
		'D sus4',
		'E 7(no3)',
		'E 7(sus4)',
		'E dim',
		'E dim #5',
		'E dim add 11',
		'E dim add 9',
		'E dim b9',
		'E dim(no5)',
		'E dim11',
		'E dim13',
		'E dim7',
		'E dim9',
		'E sus2',
		'E sus4',
		'F 7(no3)',
		'F 7(sus4)',
		'F min',
		'F min add 11',
		'F min add 9',
		'F min(no5)',
		'F min11',
		'F min13',
		'F min7',
		'F min9',
		'F sus2',
		'F sus4',
		'G 7(no3)',
		'G 7(sus4)',
		'G maj',
		'G maj add 11',
		'G maj add 9',
		'G maj(no5)',
		'G maj11',
		'G maj13',
		'G maj7',
		'G maj9',
		'G sus2',
		'G sus4'
	],
	'D# major': [
		'A# 13(sus4)',
		'A# 7(no3)',
		'A# 7(sus4)',
		'A# 9(sus4)',
		'A# maj',
		'A# maj add 11',
		'A# maj add 9',
		'A# maj(no5)',
		'A# maj11',
		'A# maj13',
		'A# maj7',
		'A# maj9',
		'A# sus2',
		'A# sus4',
		'C 7(no3)',
		'C 7(sus4)',
		'C min',
		'C min add 11',
		'C min add 9',
		'C min(no5)',
		'C min11',
		'C min13',
		'C min7',
		'C min9',
		'C sus2',
		'C sus4',
		'D 7(no3)',
		'D 7(sus4)',
		'D dim',
		'D dim add 11',
		'D dim add 9',
		'D dim(no5)',
		'D dim11',
		'D dim13',
		'D dim7',
		'D dim9',
		'D sus2',
		'D sus4',
		'D# 6(sus2)',
		'D# 6(sus4)',
		'D# 7(no3)',
		'D# 7(sus4)',
		'D# maj',
		'D# maj add 11',
		'D# maj add 9',
		'D# maj(no5)',
		'D# maj11',
		'D# maj13',
		'D# maj7',
		'D# maj9',
		'D# sus2',
		'D# sus4',
		'F 7(no3)',
		'F 7(sus4)',
		'F dim #5',
		'F dim b9',
		'F min',
		'F min add 11',
		'F min add 9',
		'F min(no5)',
		'F min11',
		'F min13',
		'F min7',
		'F min9',
		'F sus2',
		'F sus4',
		'G 7(no3)',
		'G 7(sus4)',
		'G min',
		'G min add 11',
		'G min add 9',
		'G min(no5)',
		'G min11',
		'G min13',
		'G min7',
		'G min9',
		'G sus2',
		'G sus4',
		'G# 7(no3)',
		'G# 7(sus4)',
		'G# maj',
		'G# maj add 11',
		'G# maj add 9',
		'G# maj(no5)',
		'G# maj11',
		'G# maj13',
		'G# maj7',
		'G# maj9',
		'G# sus2',
		'G# sus4'
	],
	'D# minor': [
		'A# 13(sus4)',
		'A# 7(no3)',
		'A# 7(sus4)',
		'A# 9(sus4)',
		'A# maj',
		'A# maj add 11',
		'A# maj add 9',
		'A# maj(no5)',
		'A# maj11',
		'A# maj13',
		'A# maj7',
		'A# maj9',
		'A# sus2',
		'A# sus4',
		'B 7(no3)',
		'B 7(sus4)',
		'B min',
		'B min add 11',
		'B min add 9',
		'B min(no5)',
		'B min11',
		'B min13',
		'B min7',
		'B min9',
		'B sus2',
		'B sus4',
		'C# 7(no3)',
		'C# 7(sus4)',
		'C# maj',
		'C# maj add 11',
		'C# maj add 9',
		'C# maj(no5)',
		'C# maj11',
		'C# maj13',
		'C# maj7',
		'C# maj9',
		'C# sus2',
		'C# sus4',
		'D# 6(sus2)',
		'D# 6(sus4)',
		'D# 7(no3)',
		'D# 7(sus4)',
		'D# min',
		'D# min add 11',
		'D# min add 9',
		'D# min(no5)',
		'D# min11',
		'D# min13',
		'D# min7',
		'D# min9',
		'D# sus2',
		'D# sus4',
		'F 7(no3)',
		'F 7(sus4)',
		'F dim',
		'F dim #5',
		'F dim add 11',
		'F dim add 9',
		'F dim b9',
		'F dim(no5)',
		'F dim11',
		'F dim13',
		'F dim7',
		'F dim9',
		'F sus2',
		'F sus4',
		'F# 7(no3)',
		'F# 7(sus4)',
		'F# min',
		'F# min add 11',
		'F# min add 9',
		'F# min(no5)',
		'F# min11',
		'F# min13',
		'F# min7',
		'F# min9',
		'F# sus2',
		'F# sus4',
		'G# 7(no3)',
		'G# 7(sus4)',
		'G# maj',
		'G# maj add 11',
		'G# maj add 9',
		'G# maj(no5)',
		'G# maj11',
		'G# maj13',
		'G# maj7',
		'G# maj9',
		'G# sus2',
		'G# sus4'
	],
	'E major': [
		'A 7(no3)',
		'A 7(sus4)',
		'A maj',
		'A maj add 11',
		'A maj add 9',
		'A maj(no5)',
		'A maj11',
		'A maj13',
		'A maj7',
		'A maj9',
		'A sus2',
		'A sus4',
		'B 13(sus4)',
		'B 7(no3)',
		'B 7(sus4)',
		'B 9(sus4)',
		'B maj',
		'B maj add 11',
		'B maj add 9',
		'B maj(no5)',
		'B maj11',
		'B maj13',
		'B maj7',
		'B maj9',
		'B sus2',
		'B sus4',
		'C# 7(no3)',
		'C# 7(sus4)',
		'C# min',
		'C# min add 11',
		'C# min add 9',
		'C# min(no5)',
		'C# min11',
		'C# min13',
		'C# min7',
		'C# min9',
		'C# sus2',
		'C# sus4',
		'D# 7(no3)',
		'D# 7(sus4)',
		'D# dim',
		'D# dim add 11',
		'D# dim add 9',
		'D# dim(no5)',
		'D# dim11',
		'D# dim13',
		'D# dim7',
		'D# dim9',
		'D# sus2',
		'D# sus4',
		'E 6(sus2)',
		'E 6(sus4)',
		'E 7(no3)',
		'E 7(sus4)',
		'E maj',
		'E maj add 11',
		'E maj add 9',
		'E maj(no5)',
		'E maj11',
		'E maj13',
		'E maj7',
		'E maj9',
		'E sus2',
		'E sus4',
		'F# 7(no3)',
		'F# 7(sus4)',
		'F# dim #5',
		'F# dim b9',
		'F# min',
		'F# min add 11',
		'F# min add 9',
		'F# min(no5)',
		'F# min11',
		'F# min13',
		'F# min7',
		'F# min9',
		'F# sus2',
		'F# sus4',
		'G# 7(no3)',
		'G# 7(sus4)',
		'G# min',
		'G# min add 11',
		'G# min add 9',
		'G# min(no5)',
		'G# min11',
		'G# min13',
		'G# min7',
		'G# min9',
		'G# sus2',
		'G# sus4'
	],
	'E minor': [
		'A 7(no3)',
		'A 7(sus4)',
		'A maj',
		'A maj add 11',
		'A maj add 9',
		'A maj(no5)',
		'A maj11',
		'A maj13',
		'A maj7',
		'A maj9',
		'A sus2',
		'A sus4',
		'B 13(sus4)',
		'B 7(no3)',
		'B 7(sus4)',
		'B 9(sus4)',
		'B maj',
		'B maj add 11',
		'B maj add 9',
		'B maj(no5)',
		'B maj11',
		'B maj13',
		'B maj7',
		'B maj9',
		'B sus2',
		'B sus4',
		'C 7(no3)',
		'C 7(sus4)',
		'C min',
		'C min add 11',
		'C min add 9',
		'C min(no5)',
		'C min11',
		'C min13',
		'C min7',
		'C min9',
		'C sus2',
		'C sus4',
		'D 7(no3)',
		'D 7(sus4)',
		'D maj',
		'D maj add 11',
		'D maj add 9',
		'D maj(no5)',
		'D maj11',
		'D maj13',
		'D maj7',
		'D maj9',
		'D sus2',
		'D sus4',
		'E 6(sus2)',
		'E 6(sus4)',
		'E 7(no3)',
		'E 7(sus4)',
		'E min',
		'E min add 11',
		'E min add 9',
		'E min(no5)',
		'E min11',
		'E min13',
		'E min7',
		'E min9',
		'E sus2',
		'E sus4',
		'F# 7(no3)',
		'F# 7(sus4)',
		'F# dim',
		'F# dim #5',
		'F# dim add 11',
		'F# dim add 9',
		'F# dim b9',
		'F# dim(no5)',
		'F# dim11',
		'F# dim13',
		'F# dim7',
		'F# dim9',
		'F# sus2',
		'F# sus4',
		'G 7(no3)',
		'G 7(sus4)',
		'G min',
		'G min add 11',
		'G min add 9',
		'G min(no5)',
		'G min11',
		'G min13',
		'G min7',
		'G min9',
		'G sus2',
		'G sus4'
	],
	'F major': [
		'A 7(no3)',
		'A 7(sus4)',
		'A min',
		'A min add 11',
		'A min add 9',
		'A min(no5)',
		'A min11',
		'A min13',
		'A min7',
		'A min9',
		'A sus2',
		'A sus4',
		'A# 7(no3)',
		'A# 7(sus4)',
		'A# maj',
		'A# maj add 11',
		'A# maj add 9',
		'A# maj(no5)',
		'A# maj11',
		'A# maj13',
		'A# maj7',
		'A# maj9',
		'A# sus2',
		'A# sus4',
		'C 13(sus4)',
		'C 7(no3)',
		'C 7(sus4)',
		'C 9(sus4)',
		'C maj',
		'C maj add 11',
		'C maj add 9',
		'C maj(no5)',
		'C maj11',
		'C maj13',
		'C maj7',
		'C maj9',
		'C sus2',
		'C sus4',
		'D 7(no3)',
		'D 7(sus4)',
		'D min',
		'D min add 11',
		'D min add 9',
		'D min(no5)',
		'D min11',
		'D min13',
		'D min7',
		'D min9',
		'D sus2',
		'D sus4',
		'E 7(no3)',
		'E 7(sus4)',
		'E dim',
		'E dim add 11',
		'E dim add 9',
		'E dim(no5)',
		'E dim11',
		'E dim13',
		'E dim7',
		'E dim9',
		'E sus2',
		'E sus4',
		'F 6(sus2)',
		'F 6(sus4)',
		'F 7(no3)',
		'F 7(sus4)',
		'F maj',
		'F maj add 11',
		'F maj add 9',
		'F maj(no5)',
		'F maj11',
		'F maj13',
		'F maj7',
		'F maj9',
		'F sus2',
		'F sus4',
		'G 7(no3)',
		'G 7(sus4)',
		'G dim #5',
		'G dim b9',
		'G min',
		'G min add 11',
		'G min add 9',
		'G min(no5)',
		'G min11',
		'G min13',
		'G min7',
		'G min9',
		'G sus2',
		'G sus4'
	],
	'F minor': [
		'A# 7(no3)',
		'A# 7(sus4)',
		'A# maj',
		'A# maj add 11',
		'A# maj add 9',
		'A# maj(no5)',
		'A# maj11',
		'A# maj13',
		'A# maj7',
		'A# maj9',
		'A# sus2',
		'A# sus4',
		'C 13(sus4)',
		'C 7(no3)',
		'C 7(sus4)',
		'C 9(sus4)',
		'C maj',
		'C maj add 11',
		'C maj add 9',
		'C maj(no5)',
		'C maj11',
		'C maj13',
		'C maj7',
		'C maj9',
		'C sus2',
		'C sus4',
		'C# 7(no3)',
		'C# 7(sus4)',
		'C# min',
		'C# min add 11',
		'C# min add 9',
		'C# min(no5)',
		'C# min11',
		'C# min13',
		'C# min7',
		'C# min9',
		'C# sus2',
		'C# sus4',
		'D# 7(no3)',
		'D# 7(sus4)',
		'D# maj',
		'D# maj add 11',
		'D# maj add 9',
		'D# maj(no5)',
		'D# maj11',
		'D# maj13',
		'D# maj7',
		'D# maj9',
		'D# sus2',
		'D# sus4',
		'F 6(sus2)',
		'F 6(sus4)',
		'F 7(no3)',
		'F 7(sus4)',
		'F min',
		'F min add 11',
		'F min add 9',
		'F min(no5)',
		'F min11',
		'F min13',
		'F min7',
		'F min9',
		'F sus2',
		'F sus4',
		'G 7(no3)',
		'G 7(sus4)',
		'G dim',
		'G dim #5',
		'G dim add 11',
		'G dim add 9',
		'G dim b9',
		'G dim(no5)',
		'G dim11',
		'G dim13',
		'G dim7',
		'G dim9',
		'G sus2',
		'G sus4',
		'G# 7(no3)',
		'G# 7(sus4)',
		'G# min',
		'G# min add 11',
		'G# min add 9',
		'G# min(no5)',
		'G# min11',
		'G# min13',
		'G# min7',
		'G# min9',
		'G# sus2',
		'G# sus4'
	],
	'F# major': [
		'A# 7(no3)',
		'A# 7(sus4)',
		'A# min',
		'A# min add 11',
		'A# min add 9',
		'A# min(no5)',
		'A# min11',
		'A# min13',
		'A# min7',
		'A# min9',
		'A# sus2',
		'A# sus4',
		'B 7(no3)',
		'B 7(sus4)',
		'B maj',
		'B maj add 11',
		'B maj add 9',
		'B maj(no5)',
		'B maj11',
		'B maj13',
		'B maj7',
		'B maj9',
		'B sus2',
		'B sus4',
		'C# 13(sus4)',
		'C# 7(no3)',
		'C# 7(sus4)',
		'C# 9(sus4)',
		'C# maj',
		'C# maj add 11',
		'C# maj add 9',
		'C# maj(no5)',
		'C# maj11',
		'C# maj13',
		'C# maj7',
		'C# maj9',
		'C# sus2',
		'C# sus4',
		'D# 7(no3)',
		'D# 7(sus4)',
		'D# min',
		'D# min add 11',
		'D# min add 9',
		'D# min(no5)',
		'D# min11',
		'D# min13',
		'D# min7',
		'D# min9',
		'D# sus2',
		'D# sus4',
		'F 7(no3)',
		'F 7(sus4)',
		'F dim',
		'F dim add 11',
		'F dim add 9',
		'F dim(no5)',
		'F dim11',
		'F dim13',
		'F dim7',
		'F dim9',
		'F sus2',
		'F sus4',
		'F# 6(sus2)',
		'F# 6(sus4)',
		'F# 7(no3)',
		'F# 7(sus4)',
		'F# maj',
		'F# maj add 11',
		'F# maj add 9',
		'F# maj(no5)',
		'F# maj11',
		'F# maj13',
		'F# maj7',
		'F# maj9',
		'F# sus2',
		'F# sus4',
		'G# 7(no3)',
		'G# 7(sus4)',
		'G# dim #5',
		'G# dim b9',
		'G# min',
		'G# min add 11',
		'G# min add 9',
		'G# min(no5)',
		'G# min11',
		'G# min13',
		'G# min7',
		'G# min9',
		'G# sus2',
		'G# sus4'
	],
	'F# minor': [
		'A 7(no3)',
		'A 7(sus4)',
		'A min',
		'A min add 11',
		'A min add 9',
		'A min(no5)',
		'A min11',
		'A min13',
		'A min7',
		'A min9',
		'A sus2',
		'A sus4',
		'B 7(no3)',
		'B 7(sus4)',
		'B maj',
		'B maj add 11',
		'B maj add 9',
		'B maj(no5)',
		'B maj11',
		'B maj13',
		'B maj7',
		'B maj9',
		'B sus2',
		'B sus4',
		'C# 13(sus4)',
		'C# 7(no3)',
		'C# 7(sus4)',
		'C# 9(sus4)',
		'C# maj',
		'C# maj add 11',
		'C# maj add 9',
		'C# maj(no5)',
		'C# maj11',
		'C# maj13',
		'C# maj7',
		'C# maj9',
		'C# sus2',
		'C# sus4',
		'D 7(no3)',
		'D 7(sus4)',
		'D min',
		'D min add 11',
		'D min add 9',
		'D min(no5)',
		'D min11',
		'D min13',
		'D min7',
		'D min9',
		'D sus2',
		'D sus4',
		'E 7(no3)',
		'E 7(sus4)',
		'E maj',
		'E maj add 11',
		'E maj add 9',
		'E maj(no5)',
		'E maj11',
		'E maj13',
		'E maj7',
		'E maj9',
		'E sus2',
		'E sus4',
		'F# 6(sus2)',
		'F# 6(sus4)',
		'F# 7(no3)',
		'F# 7(sus4)',
		'F# min',
		'F# min add 11',
		'F# min add 9',
		'F# min(no5)',
		'F# min11',
		'F# min13',
		'F# min7',
		'F# min9',
		'F# sus2',
		'F# sus4',
		'G# 7(no3)',
		'G# 7(sus4)',
		'G# dim',
		'G# dim #5',
		'G# dim add 11',
		'G# dim add 9',
		'G# dim b9',
		'G# dim(no5)',
		'G# dim11',
		'G# dim13',
		'G# dim7',
		'G# dim9',
		'G# sus2',
		'G# sus4'
	],
	'G major': [
		'A 7(no3)',
		'A 7(sus4)',
		'A dim #5',
		'A dim b9',
		'A min',
		'A min add 11',
		'A min add 9',
		'A min(no5)',
		'A min11',
		'A min13',
		'A min7',
		'A min9',
		'A sus2',
		'A sus4',
		'B 7(no3)',
		'B 7(sus4)',
		'B min',
		'B min add 11',
		'B min add 9',
		'B min(no5)',
		'B min11',
		'B min13',
		'B min7',
		'B min9',
		'B sus2',
		'B sus4',
		'C 7(no3)',
		'C 7(sus4)',
		'C maj',
		'C maj add 11',
		'C maj add 9',
		'C maj(no5)',
		'C maj11',
		'C maj13',
		'C maj7',
		'C maj9',
		'C sus2',
		'C sus4',
		'D 13(sus4)',
		'D 7(no3)',
		'D 7(sus4)',
		'D 9(sus4)',
		'D maj',
		'D maj add 11',
		'D maj add 9',
		'D maj(no5)',
		'D maj11',
		'D maj13',
		'D maj7',
		'D maj9',
		'D sus2',
		'D sus4',
		'E 7(no3)',
		'E 7(sus4)',
		'E min',
		'E min add 11',
		'E min add 9',
		'E min(no5)',
		'E min11',
		'E min13',
		'E min7',
		'E min9',
		'E sus2',
		'E sus4',
		'F# 7(no3)',
		'F# 7(sus4)',
		'F# dim',
		'F# dim add 11',
		'F# dim add 9',
		'F# dim(no5)',
		'F# dim11',
		'F# dim13',
		'F# dim7',
		'F# dim9',
		'F# sus2',
		'F# sus4',
		'G 6(sus2)',
		'G 6(sus4)',
		'G 7(no3)',
		'G 7(sus4)',
		'G maj',
		'G maj add 11',
		'G maj add 9',
		'G maj(no5)',
		'G maj11',
		'G maj13',
		'G maj7',
		'G maj9',
		'G sus2',
		'G sus4'
	],
	'G minor': [
		'A 7(no3)',
		'A 7(sus4)',
		'A dim',
		'A dim #5',
		'A dim add 11',
		'A dim add 9',
		'A dim b9',
		'A dim(no5)',
		'A dim11',
		'A dim13',
		'A dim7',
		'A dim9',
		'A sus2',
		'A sus4',
		'A# 7(no3)',
		'A# 7(sus4)',
		'A# min',
		'A# min add 11',
		'A# min add 9',
		'A# min(no5)',
		'A# min11',
		'A# min13',
		'A# min7',
		'A# min9',
		'A# sus2',
		'A# sus4',
		'C 7(no3)',
		'C 7(sus4)',
		'C maj',
		'C maj add 11',
		'C maj add 9',
		'C maj(no5)',
		'C maj11',
		'C maj13',
		'C maj7',
		'C maj9',
		'C sus2',
		'C sus4',
		'D 13(sus4)',
		'D 7(no3)',
		'D 7(sus4)',
		'D 9(sus4)',
		'D maj',
		'D maj add 11',
		'D maj add 9',
		'D maj(no5)',
		'D maj11',
		'D maj13',
		'D maj7',
		'D maj9',
		'D sus2',
		'D sus4',
		'D# 7(no3)',
		'D# 7(sus4)',
		'D# min',
		'D# min add 11',
		'D# min add 9',
		'D# min(no5)',
		'D# min11',
		'D# min13',
		'D# min7',
		'D# min9',
		'D# sus2',
		'D# sus4',
		'F 7(no3)',
		'F 7(sus4)',
		'F maj',
		'F maj add 11',
		'F maj add 9',
		'F maj(no5)',
		'F maj11',
		'F maj13',
		'F maj7',
		'F maj9',
		'F sus2',
		'F sus4',
		'G 6(sus2)',
		'G 6(sus4)',
		'G 7(no3)',
		'G 7(sus4)',
		'G min',
		'G min add 11',
		'G min add 9',
		'G min(no5)',
		'G min11',
		'G min13',
		'G min7',
		'G min9',
		'G sus2',
		'G sus4'
	],
	'G# major': [
		'A# 7(no3)',
		'A# 7(sus4)',
		'A# dim #5',
		'A# dim b9',
		'A# min',
		'A# min add 11',
		'A# min add 9',
		'A# min(no5)',
		'A# min11',
		'A# min13',
		'A# min7',
		'A# min9',
		'A# sus2',
		'A# sus4',
		'C 7(no3)',
		'C 7(sus4)',
		'C min',
		'C min add 11',
		'C min add 9',
		'C min(no5)',
		'C min11',
		'C min13',
		'C min7',
		'C min9',
		'C sus2',
		'C sus4',
		'C# 7(no3)',
		'C# 7(sus4)',
		'C# maj',
		'C# maj add 11',
		'C# maj add 9',
		'C# maj(no5)',
		'C# maj11',
		'C# maj13',
		'C# maj7',
		'C# maj9',
		'C# sus2',
		'C# sus4',
		'D# 13(sus4)',
		'D# 7(no3)',
		'D# 7(sus4)',
		'D# 9(sus4)',
		'D# maj',
		'D# maj add 11',
		'D# maj add 9',
		'D# maj(no5)',
		'D# maj11',
		'D# maj13',
		'D# maj7',
		'D# maj9',
		'D# sus2',
		'D# sus4',
		'F 7(no3)',
		'F 7(sus4)',
		'F min',
		'F min add 11',
		'F min add 9',
		'F min(no5)',
		'F min11',
		'F min13',
		'F min7',
		'F min9',
		'F sus2',
		'F sus4',
		'G 7(no3)',
		'G 7(sus4)',
		'G dim',
		'G dim add 11',
		'G dim add 9',
		'G dim(no5)',
		'G dim11',
		'G dim13',
		'G dim7',
		'G dim9',
		'G sus2',
		'G sus4',
		'G# 6(sus2)',
		'G# 6(sus4)',
		'G# 7(no3)',
		'G# 7(sus4)',
		'G# maj',
		'G# maj add 11',
		'G# maj add 9',
		'G# maj(no5)',
		'G# maj11',
		'G# maj13',
		'G# maj7',
		'G# maj9',
		'G# sus2',
		'G# sus4'
	],
	'G# minor': [
		'A# 7(no3)',
		'A# 7(sus4)',
		'A# dim',
		'A# dim #5',
		'A# dim add 11',
		'A# dim add 9',
		'A# dim b9',
		'A# dim(no5)',
		'A# dim11',
		'A# dim13',
		'A# dim7',
		'A# dim9',
		'A# sus2',
		'A# sus4',
		'B 7(no3)',
		'B 7(sus4)',
		'B min',
		'B min add 11',
		'B min add 9',
		'B min(no5)',
		'B min11',
		'B min13',
		'B min7',
		'B min9',
		'B sus2',
		'B sus4',
		'C# 7(no3)',
		'C# 7(sus4)',
		'C# maj',
		'C# maj add 11',
		'C# maj add 9',
		'C# maj(no5)',
		'C# maj11',
		'C# maj13',
		'C# maj7',
		'C# maj9',
		'C# sus2',
		'C# sus4',
		'D# 13(sus4)',
		'D# 7(no3)',
		'D# 7(sus4)',
		'D# 9(sus4)',
		'D# maj',
		'D# maj add 11',
		'D# maj add 9',
		'D# maj(no5)',
		'D# maj11',
		'D# maj13',
		'D# maj7',
		'D# maj9',
		'D# sus2',
		'D# sus4',
		'E 7(no3)',
		'E 7(sus4)',
		'E min',
		'E min add 11',
		'E min add 9',
		'E min(no5)',
		'E min11',
		'E min13',
		'E min7',
		'E min9',
		'E sus2',
		'E sus4',
		'F# 7(no3)',
		'F# 7(sus4)',
		'F# maj',
		'F# maj add 11',
		'F# maj add 9',
		'F# maj(no5)',
		'F# maj11',
		'F# maj13',
		'F# maj7',
		'F# maj9',
		'F# sus2',
		'F# sus4',
		'G# 6(sus2)',
		'G# 6(sus4)',
		'G# 7(no3)',
		'G# 7(sus4)',
		'G# min',
		'G# min add 11',
		'G# min add 9',
		'G# min(no5)',
		'G# min11',
		'G# min13',
		'G# min7',
		'G# min9',
		'G# sus2',
		'G# sus4'
	],
	'A major': [
		'A 6(sus2)',
		'A 6(sus4)',
		'A 7(no3)',
		'A 7(sus4)',
		'A maj',
		'A maj add 11',
		'A maj add 9',
		'A maj(no5)',
		'A maj11',
		'A maj13',
		'A maj7',
		'A maj9',
		'A sus2',
		'A sus4',
		'B 7(no3)',
		'B 7(sus4)',
		'B dim #5',
		'B dim b9',
		'B min',
		'B min add 11',
		'B min add 9',
		'B min(no5)',
		'B min11',
		'B min13',
		'B min7',
		'B min9',
		'B sus2',
		'B sus4',
		'C# 7(no3)',
		'C# 7(sus4)',
		'C# min',
		'C# min add 11',
		'C# min add 9',
		'C# min(no5)',
		'C# min11',
		'C# min13',
		'C# min7',
		'C# min9',
		'C# sus2',
		'C# sus4',
		'D 7(no3)',
		'D 7(sus4)',
		'D maj',
		'D maj add 11',
		'D maj add 9',
		'D maj(no5)',
		'D maj11',
		'D maj13',
		'D maj7',
		'D maj9',
		'D sus2',
		'D sus4',
		'E 13(sus4)',
		'E 7(no3)',
		'E 7(sus4)',
		'E 9(sus4)',
		'E maj',
		'E maj add 11',
		'E maj add 9',
		'E maj(no5)',
		'E maj11',
		'E maj13',
		'E maj7',
		'E maj9',
		'E sus2',
		'E sus4',
		'F# 7(no3)',
		'F# 7(sus4)',
		'F# min',
		'F# min add 11',
		'F# min add 9',
		'F# min(no5)',
		'F# min11',
		'F# min13',
		'F# min7',
		'F# min9',
		'F# sus2',
		'F# sus4',
		'G# 7(no3)',
		'G# 7(sus4)',
		'G# dim',
		'G# dim add 11',
		'G# dim add 9',
		'G# dim(no5)',
		'G# dim11',
		'G# dim13',
		'G# dim7',
		'G# dim9',
		'G# sus2',
		'G# sus4'
	],
	'A minor': [
		'A 6(sus2)',
		'A 6(sus4)',
		'A 7(no3)',
		'A 7(sus4)',
		'A min',
		'A min add 11',
		'A min add 9',
		'A min(no5)',
		'A min11',
		'A min13',
		'A min7',
		'A min9',
		'A sus2',
		'A sus4',
		'B 7(no3)',
		'B 7(sus4)',
		'B dim',
		'B dim #5',
		'B dim add 11',
		'B dim add 9',
		'B dim b9',
		'B dim(no5)',
		'B dim11',
		'B dim13',
		'B dim7',
		'B dim9',
		'B sus2',
		'B sus4',
		'C 7(no3)',
		'C 7(sus4)',
		'C min',
		'C min add 11',
		'C min add 9',
		'C min(no5)',
		'C min11',
		'C min13',
		'C min7',
		'C min9',
		'C sus2',
		'C sus4',
		'D 7(no3)',
		'D 7(sus4)',
		'D maj',
		'D maj add 11',
		'D maj add 9',
		'D maj(no5)',
		'D maj11',
		'D maj13',
		'D maj7',
		'D maj9',
		'D sus2',
		'D sus4',
		'E 13(sus4)',
		'E 7(no3)',
		'E 7(sus4)',
		'E 9(sus4)',
		'E maj',
		'E maj add 11',
		'E maj add 9',
		'E maj(no5)',
		'E maj11',
		'E maj13',
		'E maj7',
		'E maj9',
		'E sus2',
		'E sus4',
		'F 7(no3)',
		'F 7(sus4)',
		'F min',
		'F min add 11',
		'F min add 9',
		'F min(no5)',
		'F min11',
		'F min13',
		'F min7',
		'F min9',
		'F sus2',
		'F sus4',
		'G 7(no3)',
		'G 7(sus4)',
		'G maj',
		'G maj add 11',
		'G maj add 9',
		'G maj(no5)',
		'G maj11',
		'G maj13',
		'G maj7',
		'G maj9',
		'G sus2',
		'G sus4'
	],
	'A# major': [
		'A 7(no3)',
		'A 7(sus4)',
		'A dim',
		'A dim add 11',
		'A dim add 9',
		'A dim(no5)',
		'A dim11',
		'A dim13',
		'A dim7',
		'A dim9',
		'A sus2',
		'A sus4',
		'A# 6(sus2)',
		'A# 6(sus4)',
		'A# 7(no3)',
		'A# 7(sus4)',
		'A# maj',
		'A# maj add 11',
		'A# maj add 9',
		'A# maj(no5)',
		'A# maj11',
		'A# maj13',
		'A# maj7',
		'A# maj9',
		'A# sus2',
		'A# sus4',
		'C 7(no3)',
		'C 7(sus4)',
		'C dim #5',
		'C dim b9',
		'C min',
		'C min add 11',
		'C min add 9',
		'C min(no5)',
		'C min11',
		'C min13',
		'C min7',
		'C min9',
		'C sus2',
		'C sus4',
		'D 7(no3)',
		'D 7(sus4)',
		'D min',
		'D min add 11',
		'D min add 9',
		'D min(no5)',
		'D min11',
		'D min13',
		'D min7',
		'D min9',
		'D sus2',
		'D sus4',
		'D# 7(no3)',
		'D# 7(sus4)',
		'D# maj',
		'D# maj add 11',
		'D# maj add 9',
		'D# maj(no5)',
		'D# maj11',
		'D# maj13',
		'D# maj7',
		'D# maj9',
		'D# sus2',
		'D# sus4',
		'F 13(sus4)',
		'F 7(no3)',
		'F 7(sus4)',
		'F 9(sus4)',
		'F maj',
		'F maj add 11',
		'F maj add 9',
		'F maj(no5)',
		'F maj11',
		'F maj13',
		'F maj7',
		'F maj9',
		'F sus2',
		'F sus4',
		'G 7(no3)',
		'G 7(sus4)',
		'G min',
		'G min add 11',
		'G min add 9',
		'G min(no5)',
		'G min11',
		'G min13',
		'G min7',
		'G min9',
		'G sus2',
		'G sus4'
	],
	'A# minor': [
		'A# 6(sus2)',
		'A# 6(sus4)',
		'A# 7(no3)',
		'A# 7(sus4)',
		'A# min',
		'A# min add 11',
		'A# min add 9',
		'A# min(no5)',
		'A# min11',
		'A# min13',
		'A# min7',
		'A# min9',
		'A# sus2',
		'A# sus4',
		'C 7(no3)',
		'C 7(sus4)',
		'C dim',
		'C dim #5',
		'C dim add 11',
		'C dim add 9',
		'C dim b9',
		'C dim(no5)',
		'C dim11',
		'C dim13',
		'C dim7',
		'C dim9',
		'C sus2',
		'C sus4',
		'C# 7(no3)',
		'C# 7(sus4)',
		'C# min',
		'C# min add 11',
		'C# min add 9',
		'C# min(no5)',
		'C# min11',
		'C# min13',
		'C# min7',
		'C# min9',
		'C# sus2',
		'C# sus4',
		'D# 7(no3)',
		'D# 7(sus4)',
		'D# maj',
		'D# maj add 11',
		'D# maj add 9',
		'D# maj(no5)',
		'D# maj11',
		'D# maj13',
		'D# maj7',
		'D# maj9',
		'D# sus2',
		'D# sus4',
		'F 13(sus4)',
		'F 7(no3)',
		'F 7(sus4)',
		'F 9(sus4)',
		'F maj',
		'F maj add 11',
		'F maj add 9',
		'F maj(no5)',
		'F maj11',
		'F maj13',
		'F maj7',
		'F maj9',
		'F sus2',
		'F sus4',
		'F# 7(no3)',
		'F# 7(sus4)',
		'F# min',
		'F# min add 11',
		'F# min add 9',
		'F# min(no5)',
		'F# min11',
		'F# min13',
		'F# min7',
		'F# min9',
		'F# sus2',
		'F# sus4',
		'G# 7(no3)',
		'G# 7(sus4)',
		'G# maj',
		'G# maj add 11',
		'G# maj add 9',
		'G# maj(no5)',
		'G# maj11',
		'G# maj13',
		'G# maj7',
		'G# maj9',
		'G# sus2',
		'G# sus4'
	],
	'B major': [
		'A# 7(no3)',
		'A# 7(sus4)',
		'A# dim',
		'A# dim add 11',
		'A# dim add 9',
		'A# dim(no5)',
		'A# dim11',
		'A# dim13',
		'A# dim7',
		'A# dim9',
		'A# sus2',
		'A# sus4',
		'B 6(sus2)',
		'B 6(sus4)',
		'B 7(no3)',
		'B 7(sus4)',
		'B maj',
		'B maj add 11',
		'B maj add 9',
		'B maj(no5)',
		'B maj11',
		'B maj13',
		'B maj7',
		'B maj9',
		'B sus2',
		'B sus4',
		'C# 7(no3)',
		'C# 7(sus4)',
		'C# dim #5',
		'C# dim b9',
		'C# min',
		'C# min add 11',
		'C# min add 9',
		'C# min(no5)',
		'C# min11',
		'C# min13',
		'C# min7',
		'C# min9',
		'C# sus2',
		'C# sus4',
		'D# 7(no3)',
		'D# 7(sus4)',
		'D# min',
		'D# min add 11',
		'D# min add 9',
		'D# min(no5)',
		'D# min11',
		'D# min13',
		'D# min7',
		'D# min9',
		'D# sus2',
		'D# sus4',
		'E 7(no3)',
		'E 7(sus4)',
		'E maj',
		'E maj add 11',
		'E maj add 9',
		'E maj(no5)',
		'E maj11',
		'E maj13',
		'E maj7',
		'E maj9',
		'E sus2',
		'E sus4',
		'F# 13(sus4)',
		'F# 7(no3)',
		'F# 7(sus4)',
		'F# 9(sus4)',
		'F# maj',
		'F# maj add 11',
		'F# maj add 9',
		'F# maj(no5)',
		'F# maj11',
		'F# maj13',
		'F# maj7',
		'F# maj9',
		'F# sus2',
		'F# sus4',
		'G# 7(no3)',
		'G# 7(sus4)',
		'G# min',
		'G# min add 11',
		'G# min add 9',
		'G# min(no5)',
		'G# min11',
		'G# min13',
		'G# min7',
		'G# min9',
		'G# sus2',
		'G# sus4'
	],
	'B minor': [
		'A 7(no3)',
		'A 7(sus4)',
		'A maj',
		'A maj add 11',
		'A maj add 9',
		'A maj(no5)',
		'A maj11',
		'A maj13',
		'A maj7',
		'A maj9',
		'A sus2',
		'A sus4',
		'B 6(sus2)',
		'B 6(sus4)',
		'B 7(no3)',
		'B 7(sus4)',
		'B min',
		'B min add 11',
		'B min add 9',
		'B min(no5)',
		'B min11',
		'B min13',
		'B min7',
		'B min9',
		'B sus2',
		'B sus4',
		'C# 7(no3)',
		'C# 7(sus4)',
		'C# dim',
		'C# dim #5',
		'C# dim add 11',
		'C# dim add 9',
		'C# dim b9',
		'C# dim(no5)',
		'C# dim11',
		'C# dim13',
		'C# dim7',
		'C# dim9',
		'C# sus2',
		'C# sus4',
		'D 7(no3)',
		'D 7(sus4)',
		'D min',
		'D min add 11',
		'D min add 9',
		'D min(no5)',
		'D min11',
		'D min13',
		'D min7',
		'D min9',
		'D sus2',
		'D sus4',
		'E 7(no3)',
		'E 7(sus4)',
		'E maj',
		'E maj add 11',
		'E maj add 9',
		'E maj(no5)',
		'E maj11',
		'E maj13',
		'E maj7',
		'E maj9',
		'E sus2',
		'E sus4',
		'F# 13(sus4)',
		'F# 7(no3)',
		'F# 7(sus4)',
		'F# 9(sus4)',
		'F# maj',
		'F# maj add 11',
		'F# maj add 9',
		'F# maj(no5)',
		'F# maj11',
		'F# maj13',
		'F# maj7',
		'F# maj9',
		'F# sus2',
		'F# sus4',
		'G 7(no3)',
		'G 7(sus4)',
		'G min',
		'G min add 11',
		'G min add 9',
		'G min(no5)',
		'G min11',
		'G min13',
		'G min7',
		'G min9',
		'G sus2',
		'G sus4'
	]
}
