export const LAYOUT_ROWS: string[][] = [
	[
		'Backquote',
		'Digit1',
		'Digit2',
		'Digit3',
		'Digit4',
		'Digit5',
		'Digit6',
		'Digit7',
		'Digit8',
		'Digit9',
		'Digit0',
		'Minus',
		'Equal',
		'Backspace'
	],
	[
		'Tab',
		'KeyQ',
		'KeyW',
		'KeyE',
		'KeyR',
		'KeyT',
		'KeyY',
		'KeyU',
		'KeyI',
		'KeyO',
		'KeyP',
		'BracketLeft',
		'BracketRight',
		'Backslash'
	],
	['CapsLock', 'KeyA', 'KeyS', 'KeyD', 'KeyF', 'KeyG', 'KeyH', 'KeyJ', 'KeyK', 'KeyL', 'Semicolon', 'Quote', 'Enter'],
	['ShiftLeft', 'KeyZ', 'KeyX', 'KeyC', 'KeyV', 'KeyB', 'KeyN', 'KeyM', 'Comma', 'Period', 'Slash', 'ShiftRight'],
	['ControlLeft', 'MetaLeft', 'AltLeft', 'Space', 'AltRight', 'ControlRight']
]

export const FUNCTIONAL: QwertyKeyT[] = [
	{
		code: 'Backquote',
		key: '`',
		location: 0,
		label: '`',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: []
	},
	{
		code: 'Minus',
		key: '-',
		location: 0,
		label: '-',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: []
	},
	{
		code: 'Equal',
		key: '=',
		location: 0,
		label: '=',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: []
	},
	{
		code: 'Backspace',
		key: 'Backspace',
		location: 0,
		label: 'Backspace',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: []
	},
	{
		code: 'Tab',
		key: 'Tab',
		location: 0,
		label: 'Tab',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: []
	},
	{
		code: 'Backslash',
		key: '\\',
		location: 0,
		label: '\\',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: ['toggleMidiOutput']
	},
	{
		code: 'CapsLock',
		key: 'CapsLock',
		location: 0,
		label: 'Caps Lock',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: ['toggleChordMode']
	},
	{
		code: 'Enter',
		key: 'Enter',
		location: 0,
		label: 'Enter',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: []
	},
	{
		code: 'ShiftLeft',
		key: 'Shift',
		location: 1,
		label: 'Shift',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: ['transposeDown']
	},
	{
		code: 'ShiftRight',
		key: 'Shift',
		location: 2,
		label: 'Shift',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: ['transposeUp']
	},
	{
		code: 'ControlLeft',
		key: 'Control',
		location: 1,
		label: 'Ctrl',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: []
	},
	{
		code: 'MetaLeft',
		key: 'Meta',
		location: 1,
		label: 'Meta',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: []
	},
	{
		code: 'AltLeft',
		key: 'Alt',
		location: 1,
		label: 'Alt',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: []
	},
	{
		code: 'Space',
		key: ' ',
		location: 0,
		label: 'Space',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: []
	},
	{
		code: 'AltRight',
		key: 'Alt',
		location: 2,
		label: 'Alt',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: []
	},
	{
		code: 'ControlRight',
		key: 'Control',
		location: 2,
		label: 'Ctrl',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: []
	}
]

export const PLAYABLE: QwertyKeyT[] = [
	{
		code: 'Digit1',
		key: '1',
		location: 0,
		label: '1',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: []
	},
	{
		code: 'Digit2',
		key: '2',
		location: 0,
		label: '2',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: []
	},
	{
		code: 'Digit3',
		key: '3',
		location: 0,
		label: '3',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: []
	},
	{
		code: 'Digit4',
		key: '4',
		location: 0,
		label: '4',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: []
	},
	{
		code: 'Digit5',
		key: '5',
		location: 0,
		label: '5',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: []
	},
	{
		code: 'Digit6',
		key: '6',
		location: 0,
		label: '6',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: []
	},
	{
		code: 'Digit7',
		key: '7',
		location: 0,
		label: '7',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: []
	},
	{
		code: 'Digit8',
		key: '8',
		location: 0,
		label: '8',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: []
	},
	{
		code: 'Digit9',
		key: '9',
		location: 0,
		label: '9',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: []
	},
	{
		code: 'Digit0',
		key: '0',
		location: 0,
		label: '0',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: []
	},
	{
		code: 'KeyQ',
		key: 'q',
		location: 0,
		label: 'Q',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: []
	},
	{
		code: 'KeyW',
		key: 'w',
		location: 0,
		label: 'W',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: []
	},
	{
		code: 'KeyE',
		key: 'e',
		location: 0,
		label: 'E',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: []
	},
	{
		code: 'KeyR',
		key: 'r',
		location: 0,
		label: 'R',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: []
	},
	{
		code: 'KeyT',
		key: 't',
		location: 0,
		label: 'T',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: []
	},
	{
		code: 'KeyY',
		key: 'y',
		location: 0,
		label: 'Y',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: []
	},
	{
		code: 'KeyU',
		key: 'u',
		location: 0,
		label: 'U',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: []
	},
	{
		code: 'KeyI',
		key: 'i',
		location: 0,
		label: 'I',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: []
	},
	{
		code: 'KeyO',
		key: 'o',
		location: 0,
		label: 'O',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: []
	},
	{
		code: 'KeyP',
		key: 'p',
		location: 0,
		label: 'P',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: []
	},
	{
		code: 'BracketLeft',
		key: '[',
		location: 0,
		label: '[',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: []
	},
	{
		code: 'BracketRight',
		key: ']',
		location: 0,
		label: ']',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: []
	},
	{
		code: 'KeyA',
		key: 'a',
		location: 0,
		label: 'A',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: []
	},
	{
		code: 'KeyS',
		key: 's',
		location: 0,
		label: 'S',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: []
	},
	{
		code: 'KeyD',
		key: 'd',
		location: 0,
		label: 'D',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: []
	},
	{
		code: 'KeyF',
		key: 'f',
		location: 0,
		label: 'F',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: []
	},
	{
		code: 'KeyG',
		key: 'g',
		location: 0,
		label: 'G',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: []
	},
	{
		code: 'KeyH',
		key: 'h',
		location: 0,
		label: 'H',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: []
	},
	{
		code: 'KeyJ',
		key: 'j',
		location: 0,
		label: 'J',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: []
	},
	{
		code: 'KeyK',
		key: 'k',
		location: 0,
		label: 'K',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: []
	},
	{
		code: 'KeyL',
		key: 'l',
		location: 0,
		label: 'L',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: []
	},
	{
		code: 'Semicolon',
		key: ';',
		location: 0,
		label: ';',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: []
	},
	{
		code: 'Quote',
		key: "'",
		location: 0,
		label: "'",
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: []
	},
	{
		code: 'KeyZ',
		key: 'z',
		location: 0,
		label: 'Z',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: []
	},
	{
		code: 'KeyX',
		key: 'x',
		location: 0,
		label: 'X',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: []
	},
	{
		code: 'KeyC',
		key: 'c',
		location: 0,
		label: 'C',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: []
	},
	{
		code: 'KeyV',
		key: 'v',
		location: 0,
		label: 'V',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: []
	},
	{
		code: 'KeyB',
		key: 'b',
		location: 0,
		label: 'B',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: []
	},
	{
		code: 'KeyN',
		key: 'n',
		location: 0,
		label: 'N',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: []
	},
	{
		code: 'KeyM',
		key: 'm',
		location: 0,
		label: 'M',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: []
	},
	{
		code: 'Comma',
		key: ',',
		location: 0,
		label: ',',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: []
	},
	{
		code: 'Period',
		key: '.',
		location: 0,
		label: '.',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: []
	},
	{
		code: 'Slash',
		key: '/',
		location: 0,
		label: '/',
		altLabel: '',
		variant: 'outline',
		color: '',
		isDisabled: false,
		function: []
	}
]

export const ALL = [...FUNCTIONAL, ...PLAYABLE]
